import { getDb } from './db';

/**
 * At-rest encryption for the one genuinely sensitive value we persist: the
 * user's OpenRouter API key.
 *
 * Threat model — read this before trusting it:
 *
 * A browser extension has no OS keystore. Anything the extension can decrypt,
 * code running *as* the extension can also decrypt. What this buys us is that
 * the AES key is generated with `extractable: false`, so the raw key material
 * is held by the browser and is not readable from JavaScript at all — not via
 * `crypto.subtle.exportKey`, not by dumping the object store from devtools,
 * not by another extension that somehow reached our IndexedDB. Those routes
 * yield ciphertext.
 *
 * It does NOT protect against an attacker with read access to the browser
 * profile directory on disk, who can drive the browser's own key storage.
 * That is the honest limit and it is stated as such in PRIVACY.md.
 */

const KEY_ID = 'aes-key-v1';

export type Sealed = {
  /** AES-GCM initialisation vector, 12 bytes. */
  iv: number[];
  /** Ciphertext bytes. */
  ct: number[];
};

/** True for a value that looks like our sealed envelope. */
export function isSealed(v: unknown): v is Sealed {
  if (typeof v !== 'object' || v === null) return false;
  const o = v as Record<string, unknown>;
  return Array.isArray(o.iv) && Array.isArray(o.ct);
}

function subtle(): SubtleCrypto {
  const c = globalThis.crypto;
  if (!c?.subtle) throw new Error('WebCrypto unavailable');
  return c.subtle;
}

/**
 * Returns the extension's AES-GCM key, generating and persisting it on first
 * use. The stored CryptoKey is non-extractable; IndexedDB structured-clones it
 * without ever exposing the bytes.
 */
export async function getOrCreateKey(): Promise<CryptoKey> {
  const db = await getDb();
  const existing = await db.get('secrets', KEY_ID);
  if (existing) return existing as CryptoKey;

  const key = await subtle().generateKey({ name: 'AES-GCM', length: 256 }, false, [
    'encrypt',
    'decrypt',
  ]);
  await db.put('secrets', key, KEY_ID);
  return key;
}

export async function seal(plaintext: string): Promise<Sealed> {
  const key = await getOrCreateKey();
  const iv = globalThis.crypto.getRandomValues(new Uint8Array(12));
  const ct = await subtle().encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext),
  );
  return { iv: [...iv], ct: [...new Uint8Array(ct)] };
}

/**
 * Reverses `seal`. Returns null when the envelope cannot be opened — a key
 * regenerated by a profile reset, or a corrupted record — so a bad blob
 * degrades to "no key set" instead of throwing on every settings read.
 */
export async function unseal(sealed: Sealed): Promise<string | null> {
  try {
    const key = await getOrCreateKey();
    const plain = await subtle().decrypt(
      { name: 'AES-GCM', iv: new Uint8Array(sealed.iv) },
      key,
      new Uint8Array(sealed.ct),
    );
    return new TextDecoder().decode(plain);
  } catch {
    return null;
  }
}

/** Drops the encryption key. Any previously sealed value becomes unopenable. */
export async function _resetKeyForTests(): Promise<void> {
  const db = await getDb();
  await db.delete('secrets', KEY_ID);
}
